[mgr]
prepend_keymap = [
  { on = [ "l" ], run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = ["g", "c"], run = "noop" },
  { on = [ "g", "C" ], run = "cd ~/.config", desc = "Go ~/.config" },
  { on = [ "g", "c", "p" ], run = "cd ~/.config/pithy_configs", desc = "Go ~/.config/pithy_configs" },
  { on = [ "g", "c", "m" ], run = "cd ~/.config/mihomo", desc = "Go ~/.config/mihomo" },
  { on = [ "g", "c", "c" ], run = "cd ~/.config/clash", desc = "Go ~/.config/clash" },
  { on = [ "e", "c", "p" ], run = "shell --block -- nvim ~/.config/pithy_custom_config", desc = "Edit ~/.config/pithy_custom_config" },
  { on = [ "e", "s", "c" ], run = "shell --block -- nvim ~/.ssh/config", desc = "Edit ~/.ssh/config" },
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },

  #{{{> plugins
  # smart filter
  { on = [ "F" ], run = "plugin smart-filter", desc = "Smart filter" },
  #<}}}
]
